stages:
  - deploy

deploy:
  stage: deploy
  image: node
  script:
    - apt-get update -y && apt-get install openssh-client -y
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY"
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo "StrictHostKeyChecking no" > ~/.ssh/config
    - echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    - npm install
    - npm install -g shipit-cli@^3.0
    - npx shipit staging deploy
  environment:
    name: $CI_BUILD_REF_NAME
  only:
    - staging
    - production
